using CommunityToolkit.Mvvm.ComponentModel;
using System.Globalization;

namespace Cloris.Aion2Flow.Services;

public sealed class LocalizationService : ObservableObject, IDisposable
{
    private readonly LanguageService _languageService;

    public LocalizationService(LanguageService languageService)
    {
        _languageService = languageService;
        _languageService.LanguageChanged += OnLanguageChanged;
    }

    public string CurrentLanguage => _languageService.CurrentLanguage;

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        var language = CurrentLanguage;
        return language switch
        {
            LanguageService.English => GetEnglish(key),
            LanguageService.Korean => GetKorean(key),
            _ => GetTraditionalChinese(key)
        };
    }

    public string Format(string key, params object?[] args) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), args);

    public void Dispose()
    {
        _languageService.LanguageChanged -= OnLanguageChanged;
    }

    private void OnLanguageChanged(object? sender, string language)
    {
        OnPropertyChanged("Item[]");
        OnPropertyChanged(nameof(CurrentLanguage));
    }

    private static string GetTraditionalChinese(string key) => key switch
    {
        "Window.Title" => "Aion2Flow",
        "Status.Ready" => "就緒",
        "Battle.Empty" => "本場戰鬥",
        "Battle.Summary" => "本場戰鬥 · {0}名角色",
        "Target.Empty" => "目標: -",
        "Target.WithName" => "目標: {0}",
        "Battle.Format" => "{0:0.0}s",
        "Scope.AllBattle" => "整場戰鬥",
        "Status.DriverReady" => "WinDivert 已啟用",
        "Status.DriverIdle" => "WinDivert 未啟用",
        "Status.PortReady" => "已發現遊戲連線埠",
        "Status.PortWaiting" => "等待遊戲連線埠",
        "Status.PortIdle" => "未監視遊戲連線埠",
        "Status.Locked" => "已鎖定戰鬥連線",
        "Status.LockedLoopback" => "已鎖定 Loopback 連線",
        "Status.Unlocked" => "尚未鎖定戰鬥連線",
        "Status.RttEstimated" => "TCP 往返延遲估計",
        "Status.RttLoopback" => "目前顯示的是 Loopback / 本機代理 TCP 往返，不是遠端遊戲伺服器延遲",
        "Status.RttLoopbackProtocol" => "目前顯示的是依協議層 request/response 推得的 Loopback 延遲估計，比 TCP RTT 更接近遊戲伺服器往返，但仍屬實驗性",
        "Status.RttUnavailable" => "尚未取得延遲估計",
        "Label.CriticalRate" => "致命",
        "Label.PerfectRate" => "完美",
        "Label.SmiteRate" => "強擊",
        "Label.MultiHitRate" => "多段打擊",
        "Label.ParryRate" => "武器格擋",
        "Label.EnduranceRate" => "鐵壁",
        "Label.RegenerationRate" => "再生",
        "Label.BackRate" => "背後",
        "Label.BlockRate" => "盾牌格擋",
        "Label.EvadeRate" => "迴避",
        "Label.InvincibleRate" => "無敵",
        "Panel.Outgoing" => "造成",
        "Panel.Incoming" => "承受",
        "Panel.Damage" => "傷害",
        "Panel.Healing" => "治療",
        "Panel.Shield" => "屏障",
        "Panel.Recovery" => "治療 / 屏障",
        "Panel.Support" => "支援",
        "Panel.SupportType" => "支援類型",
        "Panel.EmptyHistory" => "沒有歸檔戰鬥",
        "Panel.EmptySkills" => "沒有技能資料",
        "Summary.Total" => "總量",
        "Summary.Dps" => "DPS",
        "Summary.Hps" => "HPS",
        "Summary.Attacks" => "攻擊次數",
        "Summary.DirectHits" => "直擊次數",
        "Summary.Hits" => "次數",
        "Summary.Skills" => "技能",
        "Summary.Crits" => "暴擊",
        "Summary.Shield" => "屏障",
        "Action.Reset" => "重置",
        "Action.Archive" => "歸檔",
        "Action.Live" => "即時",
        "Column.History" => "歷史",
        "Column.Skill" => "技能",
        "Column.Kind" => "類型",
        "Column.Total" => "總量",
        "Column.Direct" => "直擊",
        "Column.Share" => "佔比",
        "Column.Damage" => "傷害",
        "Column.Heal" => "治療",
        "Column.Hot" => "持續治療",
        "Column.DrainDamage" => "吸收傷害",
        "Column.DrainHeal" => "吸收治療",
        "Column.Shield" => "屏障",
        "Column.Attacks" => "攻擊次數",
        "Column.DirectHits" => "直擊次數",
        "Column.Hits" => "次數",
        "Column.Critical" => "致命",
        "Column.Smite" => "強擊",
        "Column.MultiHit" => "多段打擊",
        "Column.Perfect" => "完美",
        "Column.Back" => "背後",
        "Column.Parry" => "武器格擋",
        "Column.Endurance" => "鐵壁",
        "Column.Regeneration" => "再生",
        "Column.PeriodicDamage" => "持續傷害",
        "Column.PeriodicHits" => "持續次數",
        "Column.Block" => "盾牌格擋",
        "Column.Evade" => "迴避",
        "Column.Invincible" => "無敵",
        "ValueKind.Damage" => "命中",
        "ValueKind.PeriodicDamage" => "持續傷害",
        "ValueKind.Healing" => "治療",
        "ValueKind.PeriodicHealing" => "持續治療",
        "ValueKind.DrainDamage" => "吸收傷害",
        "ValueKind.DrainHealing" => "吸收治療",
        "ValueKind.Shield" => "屏障",
        "ValueKind.Support" => "支援",
        _ => key
    };

    private static string GetEnglish(string key) => key switch
    {
        "Window.Title" => "Aion2Flow",
        "Status.Ready" => "Ready",
        "Battle.Empty" => "Current Battle",
        "Battle.Summary" => "Current Battle · {0} actors",
        "Target.Empty" => "Target: -",
        "Target.WithName" => "Target: {0}",
        "Battle.Format" => "{0:0.0}s",
        "Scope.AllBattle" => "Whole Battle",
        "Status.DriverReady" => "WinDivert is active",
        "Status.DriverIdle" => "WinDivert is inactive",
        "Status.PortReady" => "Game ports detected",
        "Status.PortWaiting" => "Waiting for game ports",
        "Status.PortIdle" => "Game ports are not being monitored",
        "Status.Locked" => "Battle connection locked",
        "Status.LockedLoopback" => "Loopback connection locked",
        "Status.Unlocked" => "Battle connection not locked",
        "Status.RttEstimated" => "TCP round-trip estimate",
        "Status.RttLoopback" => "Showing loopback / local proxy TCP RTT, not remote game server latency",
        "Status.RttLoopbackProtocol" => "Showing an experimental loopback estimate derived from protocol-level request/response timing; closer to game-server RTT than TCP ACK timing",
        "Status.RttUnavailable" => "No RTT estimate yet",
        "Label.CriticalRate" => "Critical Hit",
        "Label.PerfectRate" => "Perfect Hit",
        "Label.SmiteRate" => "Smite",
        "Label.MultiHitRate" => "Multi-Hit",
        "Label.ParryRate" => "Weapon Parry",
        "Label.EnduranceRate" => "Endurance",
        "Label.RegenerationRate" => "Regeneration",
        "Label.BackRate" => "Back Attack",
        "Label.BlockRate" => "Shield Block",
        "Label.EvadeRate" => "Evade",
        "Label.InvincibleRate" => "Invincible",
        "Panel.Outgoing" => "Outgoing",
        "Panel.Incoming" => "Incoming",
        "Panel.Damage" => "Damage",
        "Panel.Healing" => "Healing",
        "Panel.Shield" => "Barrier",
        "Panel.Recovery" => "Healing / Barrier",
        "Panel.Support" => "Support",
        "Panel.SupportType" => "Support Type",
        "Panel.EmptyHistory" => "No archived battles",
        "Panel.EmptySkills" => "No skill data",
        "Summary.Total" => "Total",
        "Summary.Dps" => "DPS",
        "Summary.Hps" => "HPS",
        "Summary.Attacks" => "Attacks",
        "Summary.DirectHits" => "Direct Hits",
        "Summary.Hits" => "Hits",
        "Summary.Skills" => "Skills",
        "Summary.Crits" => "Crits",
        "Summary.Shield" => "Barrier",
        "Action.Reset" => "Reset",
        "Action.Archive" => "Archive",
        "Action.Live" => "Live",
        "Column.History" => "History",
        "Column.Skill" => "Skill",
        "Column.Kind" => "Kind",
        "Column.Total" => "Total",
        "Column.Direct" => "Direct",
        "Column.Share" => "Share",
        "Column.Damage" => "DMG",
        "Column.Heal" => "Heal",
        "Column.Hot" => "HoT",
        "Column.DrainDamage" => "Drain DMG",
        "Column.DrainHeal" => "Drain Heal",
        "Column.Shield" => "Protective Shield",
        "Column.Attacks" => "Attacks",
        "Column.DirectHits" => "Direct Hits",
        "Column.Hits" => "Hits",
        "Column.Critical" => "Crit",
        "Column.Smite" => "Smite",
        "Column.MultiHit" => "Multi-Hit",
        "Column.Perfect" => "Perfect",
        "Column.Back" => "Back Attack",
        "Column.Parry" => "Weapon Parry",
        "Column.Endurance" => "Endurance",
        "Column.Regeneration" => "Regeneration",
        "Column.PeriodicDamage" => "Periodic DMG",
        "Column.PeriodicHits" => "Periodic Hits",
        "Column.Block" => "Shield Block",
        "Column.Evade" => "Evade",
        "Column.Invincible" => "Invincible",
        "ValueKind.Damage" => "Hit",
        "ValueKind.PeriodicDamage" => "Periodic DMG",
        "ValueKind.Healing" => "Heal",
        "ValueKind.PeriodicHealing" => "HoT",
        "ValueKind.DrainDamage" => "Drain DMG",
        "ValueKind.DrainHealing" => "Drain Heal",
        "ValueKind.Shield" => "Protective Shield",
        "ValueKind.Support" => "Support",
        _ => key
    };

    private static string GetKorean(string key) => key switch
    {
        "Window.Title" => "Aion2Flow",
        "Status.Ready" => "준비",
        "Battle.Empty" => "현재 전투",
        "Battle.Summary" => "현재 전투 · {0}명",
        "Target.Empty" => "대상: -",
        "Target.WithName" => "대상: {0}",
        "Battle.Format" => "{0:0.0}s",
        "Scope.AllBattle" => "전투 전체",
        "Status.DriverReady" => "WinDivert 활성화됨",
        "Status.DriverIdle" => "WinDivert 비활성",
        "Status.PortReady" => "게임 포트 감지됨",
        "Status.PortWaiting" => "게임 포트 대기 중",
        "Status.PortIdle" => "게임 포트를 감시하지 않음",
        "Status.Locked" => "전투 연결 잠금됨",
        "Status.LockedLoopback" => "루프백 연결 잠금됨",
        "Status.Unlocked" => "전투 연결이 아직 잠기지 않음",
        "Status.RttEstimated" => "TCP 왕복 지연 추정",
        "Status.RttLoopback" => "현재 표시는 루프백 / 로컬 프록시 TCP RTT이며 원격 게임 서버 지연이 아님",
        "Status.RttLoopbackProtocol" => "현재 표시는 프로토콜 계층 request/response 타이밍으로 추정한 실험적 루프백 지연이며 TCP RTT보다 게임 서버 왕복에 더 가깝습니다",
        "Status.RttUnavailable" => "RTT 추정값 없음",
        "Label.CriticalRate" => "치명",
        "Label.PerfectRate" => "완벽",
        "Label.SmiteRate" => "강타",
        "Label.MultiHitRate" => "다단타격",
        "Label.ParryRate" => "무기막기",
        "Label.EnduranceRate" => "철벽",
        "Label.RegenerationRate" => "재생",
        "Label.BackRate" => "백",
        "Label.BlockRate" => "방패막기",
        "Label.EvadeRate" => "회피",
        "Label.InvincibleRate" => "무적",
        "Panel.Outgoing" => "가한 것",
        "Panel.Incoming" => "받은 것",
        "Panel.Damage" => "피해",
        "Panel.Healing" => "치유",
        "Panel.Shield" => "보호막",
        "Panel.Recovery" => "치유 / 보호막",
        "Panel.Support" => "지원",
        "Panel.SupportType" => "지원 유형",
        "Panel.EmptyHistory" => "보관된 전투 없음",
        "Panel.EmptySkills" => "스킬 데이터 없음",
        "Summary.Total" => "총량",
        "Summary.Dps" => "DPS",
        "Summary.Hps" => "HPS",
        "Summary.Attacks" => "공격 횟수",
        "Summary.DirectHits" => "직격 횟수",
        "Summary.Hits" => "횟수",
        "Summary.Skills" => "스킬",
        "Summary.Crits" => "치명타",
        "Summary.Shield" => "보호막",
        "Action.Reset" => "초기화",
        "Action.Archive" => "보관",
        "Action.Live" => "실시간",
        "Column.History" => "기록",
        "Column.Skill" => "스킬",
        "Column.Kind" => "종류",
        "Column.Total" => "총량",
        "Column.Direct" => "직격",
        "Column.Share" => "비율",
        "Column.Damage" => "피해",
        "Column.Heal" => "치유",
        "Column.Hot" => "지속 치유",
        "Column.DrainDamage" => "흡수 피해",
        "Column.DrainHeal" => "흡수 치유",
        "Column.Shield" => "보호막",
        "Column.Attacks" => "공격 횟수",
        "Column.DirectHits" => "직격 횟수",
        "Column.Hits" => "횟수",
        "Column.Critical" => "치명타",
        "Column.Smite" => "강타",
        "Column.MultiHit" => "다단타격",
        "Column.Perfect" => "완벽",
        "Column.Back" => "후방 공격",
        "Column.Parry" => "무기막기",
        "Column.Endurance" => "철벽",
        "Column.Regeneration" => "재생",
        "Column.PeriodicDamage" => "지속 피해",
        "Column.PeriodicHits" => "지속 횟수",
        "Column.Block" => "방패막기",
        "Column.Evade" => "회피",
        "Column.Invincible" => "무적",
        "ValueKind.Damage" => "타격",
        "ValueKind.PeriodicDamage" => "지속 피해",
        "ValueKind.Healing" => "치유",
        "ValueKind.PeriodicHealing" => "지속 치유",
        "ValueKind.DrainDamage" => "흡수 피해",
        "ValueKind.DrainHealing" => "흡수 치유",
        "ValueKind.Shield" => "보호막",
        "ValueKind.Support" => "지원",
        _ => key
    };
}
