//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloris.Aion2Flow.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloris.Aion2Flow.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string Action_Live {
            get {
                return ResourceManager.GetString("Action_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Action_Reset {
            get {
                return ResourceManager.GetString("Action_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Action_SelectAll {
            get {
                return ResourceManager.GetString("Action_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Category_Damage {
            get {
                return ResourceManager.GetString("Category_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        internal static string Category_Healing {
            get {
                return ResourceManager.GetString("Category_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protective Shield.
        /// </summary>
        internal static string Category_Shield {
            get {
                return ResourceManager.GetString("Category_Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Category_Support {
            get {
                return ResourceManager.GetString("Category_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        internal static string Column_Direct {
            get {
                return ResourceManager.GetString("Column_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Column_History {
            get {
                return ResourceManager.GetString("Column_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Column_Share {
            get {
                return ResourceManager.GetString("Column_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string Column_Skill {
            get {
                return ResourceManager.GetString("Column_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        internal static string Direction_Incoming {
            get {
                return ResourceManager.GetString("Direction_Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        internal static string Direction_Outgoing {
            get {
                return ResourceManager.GetString("Direction_Outgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string Direction_Sources {
            get {
                return ResourceManager.GetString("Direction_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        internal static string Direction_Targets {
            get {
                return ResourceManager.GetString("Direction_Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No combat data yet.
        /// </summary>
        internal static string Empty_Combatants {
            get {
                return ResourceManager.GetString("Empty_Combatants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No archived battles.
        /// </summary>
        internal static string Empty_History {
            get {
                return ResourceManager.GetString("Empty_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skill data.
        /// </summary>
        internal static string Empty_Skills {
            get {
                return ResourceManager.GetString("Empty_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacks.
        /// </summary>
        internal static string Metric_Attacks {
            get {
                return ResourceManager.GetString("Metric_Attacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        internal static string Metric_Dps {
            get {
                return ResourceManager.GetString("Metric_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Hits.
        /// </summary>
        internal static string Metric_HealingHits {
            get {
                return ResourceManager.GetString("Metric_HealingHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Skills.
        /// </summary>
        internal static string Metric_HealingSkills {
            get {
                return ResourceManager.GetString("Metric_HealingSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Count.
        /// </summary>
        internal static string Metric_HitCount {
            get {
                return ResourceManager.GetString("Metric_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPS.
        /// </summary>
        internal static string Metric_Hps {
            get {
                return ResourceManager.GetString("Metric_Hps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Hits.
        /// </summary>
        internal static string Metric_ShieldHits {
            get {
                return ResourceManager.GetString("Metric_ShieldHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Skills.
        /// </summary>
        internal static string Metric_ShieldSkills {
            get {
                return ResourceManager.GetString("Metric_ShieldSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Metric_Skills {
            get {
                return ResourceManager.GetString("Metric_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Metric_Total {
            get {
                return ResourceManager.GetString("Metric_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMG.
        /// </summary>
        internal static string MetricShort_Damage {
            get {
                return ResourceManager.GetString("MetricShort_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drain Heal.
        /// </summary>
        internal static string MetricShort_DrainHeal {
            get {
                return ResourceManager.GetString("MetricShort_DrainHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        internal static string MetricShort_Heal {
            get {
                return ResourceManager.GetString("MetricShort_Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoT.
        /// </summary>
        internal static string MetricShort_Hot {
            get {
                return ResourceManager.GetString("MetricShort_Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic DMG.
        /// </summary>
        internal static string MetricShort_PeriodicDamage {
            get {
                return ResourceManager.GetString("MetricShort_PeriodicDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Hits.
        /// </summary>
        internal static string MetricShort_PeriodicHits {
            get {
                return ResourceManager.GetString("MetricShort_PeriodicHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Absorbed.
        /// </summary>
        internal static string MetricShort_ShieldAbsorbed {
            get {
                return ResourceManager.GetString("MetricShort_ShieldAbsorbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Attack.
        /// </summary>
        internal static string Stat_Back {
            get {
                return ResourceManager.GetString("Stat_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Block.
        /// </summary>
        internal static string Stat_Block {
            get {
                return ResourceManager.GetString("Stat_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string Stat_Critical {
            get {
                return ResourceManager.GetString("Stat_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endurance.
        /// </summary>
        internal static string Stat_Endurance {
            get {
                return ResourceManager.GetString("Stat_Endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evade.
        /// </summary>
        internal static string Stat_Evade {
            get {
                return ResourceManager.GetString("Stat_Evade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invincible.
        /// </summary>
        internal static string Stat_Invincible {
            get {
                return ResourceManager.GetString("Stat_Invincible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Hit.
        /// </summary>
        internal static string Stat_MultiHit {
            get {
                return ResourceManager.GetString("Stat_MultiHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Parry.
        /// </summary>
        internal static string Stat_Parry {
            get {
                return ResourceManager.GetString("Stat_Parry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        internal static string Stat_Perfect {
            get {
                return ResourceManager.GetString("Stat_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regeneration.
        /// </summary>
        internal static string Stat_Regeneration {
            get {
                return ResourceManager.GetString("Stat_Regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smite.
        /// </summary>
        internal static string Stat_Smite {
            get {
                return ResourceManager.GetString("Stat_Smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinDivert is inactive.
        /// </summary>
        internal static string Status_DriverIdle {
            get {
                return ResourceManager.GetString("Status_DriverIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinDivert is active.
        /// </summary>
        internal static string Status_DriverReady {
            get {
                return ResourceManager.GetString("Status_DriverReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency estimated from combat packets (proxy mode).
        /// </summary>
        internal static string Status_LatencyEstimatedFromCombat {
            get {
                return ResourceManager.GetString("Status_LatencyEstimatedFromCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle connection locked.
        /// </summary>
        internal static string Status_Locked {
            get {
                return ResourceManager.GetString("Status_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle connection locked (proxy mode).
        /// </summary>
        internal static string Status_LockedProxy {
            get {
                return ResourceManager.GetString("Status_LockedProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ports are not being monitored.
        /// </summary>
        internal static string Status_PortIdle {
            get {
                return ResourceManager.GetString("Status_PortIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ports detected.
        /// </summary>
        internal static string Status_PortReady {
            get {
                return ResourceManager.GetString("Status_PortReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for game ports.
        /// </summary>
        internal static string Status_PortWaiting {
            get {
                return ResourceManager.GetString("Status_PortWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP round-trip estimate.
        /// </summary>
        internal static string Status_RttEstimated {
            get {
                return ResourceManager.GetString("Status_RttEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RTT estimate yet.
        /// </summary>
        internal static string Status_RttUnavailable {
            get {
                return ResourceManager.GetString("Status_RttUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle connection not locked.
        /// </summary>
        internal static string Status_Unlocked {
            get {
                return ResourceManager.GetString("Status_Unlocked", resourceCulture);
            }
        }
    }
}
